### PR TITLE
Added DFS for Connected Graph with README.md file

### PR DESCRIPTION
**Pull request by D-Anir**
- Added DFS code for connected graph
- User can create graph using class methods
- User can run dfs method with a valid vertex and see the output

### CODE REVIEW

**Comment by LakshaySK106** [comment]
You must have created a Cpp folder inside "Graph" directory.
Also, remove .exe file
Thank you

**Comment by D-Anir** [comment]
Sure!
Can I make these changes and make a new PR?
Or can I add the commits to the existing PR only?

**Comment by LakshaySK106** [comment]
To the existing PR

**Comment by D-Anir** [comment]
@LakshaySK106 
I have made the required changes as you mentioned. Please review them. Thanks!

**Pull request merged**
