### PR TITLE
Adding iterative merge sort

### PR DESCRIPTION
**Pull request by geetanjaliverma**

### CODE REVIEW

**Review by LakshaySK106 — CHANGES_REQUESTED** [review]
You must have created a "Python" folder inside the "Sorting" directory if isn't exists.
Also, write some descriptions while making PR.

**Review by geetanjaliverma — COMMENTED** [review]
added folder named python with merge sort in it

**Comment by LakshaySK106** [comment]
ooooooooooooof💀
This must be like Sorting->Python->your_file.
Try looking at contribution guidelines before making PR

**Comment by geetanjaliverma** [comment]
Okay will keep that in mind next time.

**Review by LakshaySK106 — APPROVED** [review]
Looks good👍

**Comment by LakshaySK106** [comment]
Thanks for your contribution. Append your name to the contributors.md file following the mentioned format.

**Pull request merged**
