### PR TITLE
Created NQueen Problem

### PR DESCRIPTION
**Pull request by roshan2152**
@LakshaySK106  Please verify and if everything is fine then please merge my file in your repository using hacktoberfest label.

### CODE REVIEW

**Comment by LakshaySK106** [comment]
Create a new folder "Cpp" inside "Backtracking" directory.
Thankyou

**Comment by roshan2152** [comment]
@LakshaySK106  Changes have been made as per your requirements.

**Comment by roshan2152** [comment]
@LakshaySK106 Please merge this.

**Comment by roshan2152** [comment]
@LakshaySK106  Please assign me before merging this file. Thank you

**Comment by LakshaySK106** [comment]
Add your name to the contributors.md following the format
Thanks.

**Pull request merged**
