### PR TITLE
added tree programs 

### PR DESCRIPTION
**Pull request by diva-21**
Added Morris and vertical Traversal of Binary Trees in cpp

### CODE REVIEW

**Comment by diva-21** [comment]
Added tree,backtracking,graph programs in cpp
Kindly review this @LakshaySK106

**Review by LakshaySK106 — APPROVED** [review]

**Comment by LakshaySK106** [comment]
Looks good. Made a few changes in the "no_of_provinces.cpp" file.
Now you make another commit here. I'll approve and merge

**Comment by LakshaySK106** [comment]
Thanks for your contributions

**Comment by diva-21** [comment]
> Thanks for your contributions

Your welcome @LakshaySK106

**Pull request merged**
