### PR TITLE
Added trie data structure

### PR DESCRIPTION
**Pull request by sampaddey**
Please verify my PR.

### CODE REVIEW

**Comment by sampaddey** [comment]
I create a trie folder. Inside the trie folder, I create a file in which I write my code.

**Comment by LakshaySK106** [comment]
Inside the Trie folder, you must have created a language folder.
In your case it is Cpp.
Take a look at contributing.md file
Thanks

**Comment by sampaddey** [comment]
I did all necessary changes, now please review my PR.

**Review by LakshaySK106 — APPROVED** [review]

**Comment by LakshaySK106** [comment]
Looks good👍

**Pull request merged**
