### PR TITLE
Added Floyd Warshall Algorithm

### PR DESCRIPTION
**Pull request by D-Anir**
- Created a separate directory for the algorithm
- Added the algorithm
- Added README for better understanding

### CODE REVIEW

**Comment by LakshaySK106** [comment]
Looks good👍

**Comment by LakshaySK106** [comment]
Add your name to the contributors.md

**Comment by D-Anir** [comment]
> 

Sure, do I change the contributors' file and submit another PR?

**Comment by LakshaySK106** [comment]
Yes and following the format

**Pull request merged**
